<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="st" nsURI="https://www.xxx.xxx/st/" nsPrefix="st">
  <eSubpackages name="basics" nsURI="https://www.xxx.xxx/st/basics/" nsPrefix="basics">
    <eClassifiers xsi:type="ecore:EClass" name="Name" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//basics/Namespace"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Initializer" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//basics/Namespace"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Exprement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//basics/Namespace"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Namespace">
      <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//declarations/POUDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="declType" eType="#//basics/DeclType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DeclType">
      <eLiterals name="GLOBAL"/>
      <eLiterals name="PROGRAM" value="1"/>
      <eLiterals name="FUNCTION" value="2"/>
      <eLiterals name="FB" value="3"/>
      <eLiterals name="METHOD" value="4"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="elements" nsURI="https://www.xxx.xxx/st/elemetns/" nsPrefix="elements">
    <eClassifiers xsi:type="ecore:EClass" name="Literal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//elements/LiteralType"
          defaultValueLiteral="INTEGER"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="LiteralType">
      <eLiterals name="INTEGER"/>
      <eLiterals name="REAL" value="1"/>
      <eLiterals name="BOOLEAN" value="3"/>
      <eLiterals name="TYPED" value="4"/>
      <eLiterals name="SINGLE_BYTE_CHAR" value="5" literal="SINGLE_BYTE_CHAR"/>
      <eLiterals name="DOUBLE_BYTE_CHAR" value="6"/>
      <eLiterals name="TIME" value="7"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//basics/Name"/>
    <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//basics/Name">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableList" lowerBound="1"
          eType="#//variables/VariableList" eOpposite="#//variables/VariableList/variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//elements/Type"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="null"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="POU" abstract="true" eSuperTypes="#//basics/Name">
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" eType="#//declarations/POUDeclaration"
          eOpposite="#//declarations/POUDeclaration/POU"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="literals" nsURI="https://www.xxx.xxx/st/literals/" nsPrefix="literals">
    <eClassifiers xsi:type="ecore:EClass" name="NumericLiteral" eSuperTypes="#//elements/Literal"/>
    <eClassifiers xsi:type="ecore:EClass" name="CharLiteral" eSuperTypes="#//elements/Literal"/>
    <eClassifiers xsi:type="ecore:EClass" name="TimeLiteral" eSuperTypes="#//elements/Literal"/>
    <eClassifiers xsi:type="ecore:EClass" name="QuoteValue" eSuperTypes="#//elements/Literal">
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumValue" eType="#//elements/Literal"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="quoteType" eType="#//elements/Type"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="initializer" nsURI="https://www.xxx.xxx/st/initializers/" nsPrefix="initializer">
    <eClassifiers xsi:type="ecore:EClass" name="VariableInitializer" abstract="true"
        eSuperTypes="#//basics/Initializer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//elements/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="noNameType" eType="#//declarations/TypeDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableList" lowerBound="1"
          eType="#//variables/VariableList" containment="true" eOpposite="#//variables/VariableList/initializer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1"
          eType="#//declarations/VariableDeclaration" eOpposite="#//declarations/VariableDeclaration/initializer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleInit" eSuperTypes="#//initializer/VariableInitializer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//expressions/Expression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubrangeInit" eSuperTypes="#//initializer/VariableInitializer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//expressions/Expression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumInit" eSuperTypes="#//initializer/VariableInitializer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//elements/Literal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArraySpecInit" eSuperTypes="#//initializer/VariableInitializer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arrayInit" eType="#//initializer/ArrayInit"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayInit">
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
          eType="#//initializer/ArrayElemInit"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayElemInit">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="struct" eType="#//initializer/StructInit"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="array" eType="#//initializer/ArrayInit"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expressions/Expression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="noNameType" eType="#//declarations/TypeDeclaration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructSpecInit" eSuperTypes="#//initializer/VariableInitializer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="structInit" eType="#//initializer/StructInit"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructInit">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elemInit" upperBound="-1"
          eType="#//initializer/StructElemInit"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructElemInit" eSuperTypes="#//basics/Name">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="noNameType" eType="#//declarations/TypeDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expressions/Expression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="array" eType="#//initializer/ArrayInit"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="struct" eType="#//initializer/StructInit"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="types" nsURI="https://www.xxx.xxx/st/types/" nsPrefix="types">
    <eClassifiers xsi:type="ecore:EEnum" name="PreDefinedEDType">
      <eLiterals name="BOOL"/>
      <eLiterals name="SINT" value="1"/>
      <eLiterals name="INT" value="2" literal="INT"/>
      <eLiterals name="DINT" value="3"/>
      <eLiterals name="LINT" value="4"/>
      <eLiterals name="USINT" value="5"/>
      <eLiterals name="UINT" value="6"/>
      <eLiterals name="UDINT" value="7"/>
      <eLiterals name="ULINT" value="8"/>
      <eLiterals name="REAL" value="9"/>
      <eLiterals name="LREAL" value="10"/>
      <eLiterals name="TIME" value="11"/>
      <eLiterals name="LTIME" value="12"/>
      <eLiterals name="DATE" value="13"/>
      <eLiterals name="LDATE" value="14"/>
      <eLiterals name="TOD" value="15"/>
      <eLiterals name="LTOD" value="16"/>
      <eLiterals name="DT" value="17"/>
      <eLiterals name="LDT" value="18"/>
      <eLiterals name="STRING" value="19"/>
      <eLiterals name="WSTRING" value="20"/>
      <eLiterals name="CHAR" value="21"/>
      <eLiterals name="WCHAR" value="22"/>
      <eLiterals name="BYTE" value="23"/>
      <eLiterals name="WORD" value="24"/>
      <eLiterals name="DWORD" value="25"/>
      <eLiterals name="LWORD" value="26"/>
      <eLiterals name="VOID" value="27"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PreDefinedGDType"/>
    <eClassifiers xsi:type="ecore:EClass" name="ElementaryDataType" eSuperTypes="#//elements/Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//types/PreDefinedEDType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GenericDataType" eSuperTypes="#//elements/Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//types/PreDefinedGDType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UserDefinedDataType" eSuperTypes="#//elements/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeDeclaration" lowerBound="1"
          eType="#//declarations/TypeDeclaration" eOpposite="#//declarations/TypeDeclaration/type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubrangeType" eSuperTypes="#//types/UserDefinedDataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnumType" eSuperTypes="#//types/UserDefinedDataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayType" eSuperTypes="#//types/UserDefinedDataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="StructType" eSuperTypes="#//types/UserDefinedDataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockType" eSuperTypes="#//types/UserDefinedDataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1"
          eType="#//declarations/FunctionBlockDeclaration"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="variables" nsURI="https://www.xxx.xxx/st/variables/" nsPrefix="variables">
    <eClassifiers xsi:type="ecore:EClass" name="VariableList">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
          eType="#//elements/Variable" containment="true" eOpposite="#//elements/Variable/variableList"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initializer" lowerBound="1"
          eType="#//initializer/VariableInitializer" eOpposite="#//initializer/VariableInitializer/variableList"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//elements/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//basics/Namespace"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DirectVariable" eSuperTypes="#//elements/Variable"/>
    <eClassifiers xsi:type="ecore:EClass" name="SubscriptVariable" eSuperTypes="#//elements/Variable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subscript" lowerBound="1"
          upperBound="-1" eType="#//expressions/Expression"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="pous" nsURI="https://www.xxx.xxx/st/pous/" nsPrefix="pous">
    <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//elements/POU"/>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionBlock" eSuperTypes="#//elements/POU"/>
    <eClassifiers xsi:type="ecore:EClass" name="Program" eSuperTypes="#//elements/POU"/>
    <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//elements/POU"/>
  </eSubpackages>
  <eSubpackages name="declarations" nsURI="https://www.xxx.xxx/st/declarations/" nsPrefix="declarations">
    <eClassifiers xsi:type="ecore:EClass" name="Declaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//basics/Namespace"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeDeclList">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeDeclatation" upperBound="-1"
          eType="#//declarations/TypeDeclaration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeDeclaration" eSuperTypes="#//declarations/Declaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//types/UserDefinedDataType" derived="true" containment="true" eOpposite="#//types/UserDefinedDataType/typeDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeAccess" eType="#//elements/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Subrange">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lowerBound" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="upperBound" lowerBound="1"
          eType="#//expressions/Expression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubrangeTypeDecl" eSuperTypes="#//declarations/TypeDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="baseType" lowerBound="1"
          eType="#//types/ElementaryDataType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subrange" lowerBound="1"
          eType="#//declarations/Subrange" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumTypeDecl" eSuperTypes="#//declarations/TypeDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumValue" upperBound="-1"
          eType="#//elements/Literal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayTypeDecl" eSuperTypes="#//declarations/TypeDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subrange" upperBound="-1"
          eType="#//declarations/Subrange"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="insideType" lowerBound="1"
          eType="#//elements/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructTypeDecl" eSuperTypes="#//declarations/TypeDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
          eType="#//declarations/StructElemDecl"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructElemDecl" eSuperTypes="#//basics/Name">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="noNameType" eType="#//declarations/TypeDeclaration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="VariableSection">
      <eLiterals name="VAR"/>
      <eLiterals name="VAR_INPUT" value="1"/>
      <eLiterals name="VAR_OUTPUT" value="2"/>
      <eLiterals name="VAR_IN_OUT" value="3"/>
      <eLiterals name="VAR_EXTERNAL" value="4"/>
      <eLiterals name="VAR_GLOBAL" value="5"/>
      <eLiterals name="VAR_ACCESS" value="6"/>
      <eLiterals name="VAR_TEMP" value="7"/>
      <eLiterals name="VAR_CONFIG" value="8"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="VariableQualifier">
      <eLiterals name="NULL"/>
      <eLiterals name="RETAIN" value="1"/>
      <eLiterals name="NON_RETAIN" value="2"/>
      <eLiterals name="PROTECTED" value="3"/>
      <eLiterals name="PUBLIC" value="4"/>
      <eLiterals name="PRIVATE" value="5"/>
      <eLiterals name="INTERNAL" value="6"/>
      <eLiterals name="CONSTANT" value="7"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="#//declarations/Declaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="section" eType="#//declarations/VariableSection"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" eType="#//declarations/VariableQualifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initializer" upperBound="-1"
          eType="#//initializer/VariableInitializer" containment="true" eOpposite="#//initializer/VariableInitializer/declaration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Specifier">
      <eLiterals name="PUBLIC"/>
      <eLiterals name="PRIVATE" value="1"/>
      <eLiterals name="INTERNAL" value="2"/>
      <eLiterals name="PROTECTED" value="3"/>
      <eLiterals name="FINAL" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="POUDeclaration" eSuperTypes="#//declarations/Declaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="POU" eType="#//elements/POU"
          containment="true" eOpposite="#//elements/POU/declaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
          eType="#//elements/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="function" upperBound="-1"
          eType="#//pous/Function"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="method" upperBound="-1"
          eType="#//pous/Method"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodDeclaration" eSuperTypes="#//declarations/POUDeclaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifier" eType="#//declarations/Specifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclaration"
          upperBound="-1" eType="#//declarations/VariableDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//statements/StatementBody"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionDeclaration" eSuperTypes="#//declarations/POUDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclaration"
          upperBound="-1" eType="#//declarations/VariableDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//statements/StatementBody"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Inheritance">
      <eLiterals name="EXTENDS"/>
      <eLiterals name="OVERRIDE" value="1"/>
      <eLiterals name="ABSTRACT" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Interface">
      <eLiterals name="IMPLEMENTS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockDeclaration" eSuperTypes="#//declarations/TypeDeclaration #//declarations/POUDeclaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="inheritance" eType="#//declarations/Inheritance"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interface" eType="#//declarations/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclaration"
          upperBound="-1" eType="#//declarations/VariableDeclaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="methodDeclaration" upperBound="-1"
          eType="#//declarations/MethodDeclaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//statements/StatementBody"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProgramDeclaration" eSuperTypes="#//declarations/POUDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclaration"
          upperBound="-1" eType="#//declarations/VariableDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//statements/StatementBody"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="expressions" nsURI="https://www.xxx.xxx/st/expressions/" nsPrefix="expressions">
    <eClassifiers xsi:type="ecore:EEnum" name="UnaryOperator">
      <eLiterals name="PARENTHESES"/>
      <eLiterals name="DEREFERENCE" value="1"/>
      <eLiterals name="NEGATION" value="2"/>
      <eLiterals name="UNRAYPLUS" value="3"/>
      <eLiterals name="COMPLEMENT" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BinaryOperator">
      <eLiterals name="EXPONENTIATION"/>
      <eLiterals name="MULTIPLY" value="1"/>
      <eLiterals name="DIVIDE" value="2"/>
      <eLiterals name="MODULO" value="3"/>
      <eLiterals name="ADD" value="4" literal="+"/>
      <eLiterals name="SUBSTRACT" value="5"/>
      <eLiterals name="EQUAL" value="6"/>
      <eLiterals name="INEQUAL" value="7"/>
      <eLiterals name="LESS_THAN" value="8"/>
      <eLiterals name="LESS_THAN_OR_EQUAL" value="9"/>
      <eLiterals name="GREATER_THAN" value="10"/>
      <eLiterals name="GTEATER_THAN_OR_EQUAL" value="11"/>
      <eLiterals name="BOOLEAN_AND" value="12"/>
      <eLiterals name="BOOLEAN_EXCLUSIVE_OR" value="13"/>
      <eLiterals name="BOOLEAN_OR" value="14"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//basics/Exprement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableExpression" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          eType="#//elements/Variable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralExpression" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="literal" lowerBound="1"
          eType="#//elements/Literal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QuotevalueExpression" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="quoteValue" eType="#//literals/QuoteValue"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//expressions/Expression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
          eType="#//expressions/Parameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//pous/Function"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Invocation" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//expressions/Expression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
          eType="#//expressions/Parameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="#//pous/Method"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instanceName" eType="#//expressions/FBInstanceName"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//basics/Name">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expressions/Expression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//expressions/UnaryOperator"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//expressions/BinaryOperator"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="firstExpression" lowerBound="1"
          eType="#//expressions/Expression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="secondExpression" lowerBound="1"
          eType="#//expressions/Expression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FBInstanceName">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="varName" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="#//pous/Method"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="#//elements/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elemVar" eType="#//elements/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//elements/Type"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="statements" nsURI="https://www.xxx.xxx/st/statements/" nsPrefix="statements">
    <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="#//basics/Exprement"/>
    <eClassifiers xsi:type="ecore:EClass" name="StatementBody">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statement" upperBound="-1"
          eType="#//statements/Statement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//basics/Namespace"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssignmentStatement" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          eType="#//elements/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expressions/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="quoteValue" eType="#//literals/QuoteValue"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubprogStatement" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="functionCall" eType="#//expressions/FunctionCall"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="invocation" eType="#//expressions/Invocation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenStatement" eType="#//statements/StatementBody"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseIfStatement" upperBound="-1"
          eType="#//statements/IfStatement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseStatement" eType="#//statements/StatementBody"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GroupStatement" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exprLabel" upperBound="-1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subrangeLabel" upperBound="-1"
          eType="#//elements/Type" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statementBody" eType="#//statements/StatementBody"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CaseStatement" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="selector" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="groupStatement" upperBound="-1"
          eType="#//statements/GroupStatement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseStatement" eType="#//statements/StatementBody"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ForStatement" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlVariable" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startExpression" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endExpression" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stepExpression" eType="#//expressions/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statementBody" eType="#//statements/StatementBody"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WhileStatement" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statementBody" eType="#//statements/StatementBody"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RepeatStatement" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statementBody" eType="#//statements/StatementBody"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExitStatement" eSuperTypes="#//statements/Statement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReturnStatement" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expressions/Expression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContinueStatement" eSuperTypes="#//statements/Statement"/>
  </eSubpackages>
</ecore:EPackage>
