<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="api" nsURI="https://www.formaltech.com/st/" nsPrefix="api">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodels" upperBound="-1"
        eType="#//declarations/Declaration"/>
  </eClassifiers>
  <eSubpackages name="basics" nsURI="https://www.formaltech.com/st/api/basics/" nsPrefix="basics">
    <eClassifiers xsi:type="ecore:EClass" name="Exprement" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConstVar"/>
    <eClassifiers xsi:type="ecore:EClass" name="Comment">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LabelOrIndex"/>
    <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//basics/LabelOrIndex">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="types" nsURI="https://www.formaltech.com/st/api/types/" nsPrefix="types">
    <eClassifiers xsi:type="ecore:EClass" name="TypeDefinition" abstract="true"/>
    <eClassifiers xsi:type="ecore:EEnum" name="PreDefinedEDType">
      <eLiterals name="BOOL"/>
      <eLiterals name="SINT" value="1"/>
      <eLiterals name="INT" value="2" literal="INT"/>
      <eLiterals name="DINT" value="3"/>
      <eLiterals name="LINT" value="4"/>
      <eLiterals name="USINT" value="5"/>
      <eLiterals name="UINT" value="6"/>
      <eLiterals name="UDINT" value="7"/>
      <eLiterals name="ULINT" value="8"/>
      <eLiterals name="REAL" value="9"/>
      <eLiterals name="LREAL" value="10"/>
      <eLiterals name="TIME" value="11"/>
      <eLiterals name="LTIME" value="12"/>
      <eLiterals name="DATE" value="13"/>
      <eLiterals name="LDATE" value="14"/>
      <eLiterals name="TOD" value="15"/>
      <eLiterals name="LTOD" value="16"/>
      <eLiterals name="DT" value="17"/>
      <eLiterals name="LDT" value="18"/>
      <eLiterals name="STRING" value="19"/>
      <eLiterals name="WSTRING" value="20"/>
      <eLiterals name="CHAR" value="21"/>
      <eLiterals name="WCHAR" value="22"/>
      <eLiterals name="BYTE" value="23"/>
      <eLiterals name="WORD" value="24"/>
      <eLiterals name="DWORD" value="25"/>
      <eLiterals name="LWORD" value="26"/>
      <eLiterals name="VOID" value="27"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PreDefinedGDType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Named" eSuperTypes="#//types/TypeDefinition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//declarations/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Subrange" eSuperTypes="#//types/TypeDefinition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lower" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="upper" lowerBound="1"
          eType="#//expressions/Expression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//declarations/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Enum" eSuperTypes="#//types/TypeDefinition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
          eType="#//types/EnumElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//declarations/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expressions/Expression"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Array" eSuperTypes="#//types/TypeDefinition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="index" upperBound="-1"
          eType="#//expressions/Index"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//declarations/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Struct" eSuperTypes="#//types/TypeDefinition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//types/StructElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructElement" eSuperTypes="#//basics/LabelOrIndex">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//declarations/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//basics/Label"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="declarations" nsURI="https://www.formaltech.com/st/api/declarations/"
      nsPrefix="declarations">
    <eClassifiers xsi:type="ecore:EClass" name="Declaration" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//declarations/Declaration #//basics/ConstVar">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//declarations/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//expressions/Expression"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="section" eType="#//declarations/VariableSection"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessor" eType="#//declarations/AccessSpecifier"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistence" eType="#//declarations/PersistenceQualifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//declarations/Declaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//types/TypeDefinition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="POU" abstract="true" eSuperTypes="#//declarations/Declaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returns" upperBound="-1"
          eType="#//declarations/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//declarations/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="locals" upperBound="-1"
          eType="#//declarations/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" eType="#//statements/Statements"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionBlock" eSuperTypes="#//declarations/POU">
      <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
          eType="#//declarations/Method" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessFlag" eType="#//declarations/AccessFlag"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//declarations/POU #//basics/ConstVar">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessor" eType="#//declarations/AccessSpecifier"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessFlag" eType="#//declarations/AccessFlag"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//declarations/POU #//basics/ConstVar"/>
    <eClassifiers xsi:type="ecore:EClass" name="Program" eSuperTypes="#//declarations/POU #//basics/ConstVar"/>
    <eClassifiers xsi:type="ecore:EClass" name="Namespace" eSuperTypes="#//declarations/Declaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//declarations/Declaration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="VariableSection">
      <eLiterals name="VAR"/>
      <eLiterals name="VAR_INPUT" value="1"/>
      <eLiterals name="VAR_OUTPUT" value="2"/>
      <eLiterals name="VAR_IN_OUT" value="3"/>
      <eLiterals name="VAR_EXTERNAL" value="4"/>
      <eLiterals name="VAR_GLOBAL" value="5"/>
      <eLiterals name="VAR_ACCESS" value="6"/>
      <eLiterals name="VAR_TEMP" value="7"/>
      <eLiterals name="VAR_CONFIG" value="8"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ConstantQualifier">
      <eLiterals name="CONSTANT"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PersistenceQualifier">
      <eLiterals name="RETAIN"/>
      <eLiterals name="NON_RETAIN" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AccessSpecifier">
      <eLiterals name="PUBLIC"/>
      <eLiterals name="PROTECTED" value="1"/>
      <eLiterals name="INTERNAL" value="2"/>
      <eLiterals name="PRIVATE" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AccessFlag">
      <eLiterals name="FINAL"/>
      <eLiterals name="ABSTRUCT"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="expressions" nsURI="https://www.formaltech.com/st/api/expressions/"
      nsPrefix="expressions">
    <eClassifiers xsi:type="ecore:EEnum" name="Numeric">
      <eLiterals name="INTEGER"/>
      <eLiterals name="REAL" value="1"/>
      <eLiterals name="REAL_WITH_EXPONENT" value="2"/>
      <eLiterals name="BINARY" value="3" literal="BINARY"/>
      <eLiterals name="OCTAL" value="4"/>
      <eLiterals name="HEXADECIMAL" value="5"/>
      <eLiterals name="BOOLEAN_ZERO_AND_ONE" value="6" literal="BOOLEAN_ZERO_AND_ONE"/>
      <eLiterals name="BOOLEAN_FALSE_AND_TRUE" value="7"/>
      <eLiterals name="TYPED" value="8"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Character">
      <eLiterals name="SINGLE_BYTE"/>
      <eLiterals name="DOUBLE_BYTE" value="1"/>
      <eLiterals name="SINGLE_BYTE_TYPED" value="2"/>
      <eLiterals name="DOUBLE_BYTE_TYPED" value="3"/>
      <eLiterals name="TWO_CHARACTER_COMBINATIONS" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Time">
      <eLiterals name="DURATION_ABBREVIATIONS"/>
      <eLiterals name="DURATION_WITHOUT_UNDERSCORE" value="1"/>
      <eLiterals name="DURATION_WITH_UNDERSCORE" value="2"/>
      <eLiterals name="DATE_AND_TIME_OF_DAY" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="UnaryOperator">
      <eLiterals name="PARENTHESES" literal="()"/>
      <eLiterals name="DEREFERENCE" value="1" literal="^"/>
      <eLiterals name="NEGATION" value="2" literal="-"/>
      <eLiterals name="UNRAYPLUS" value="3" literal="+"/>
      <eLiterals name="COMPLEMENT" value="4" literal="NOT"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BinaryOperator">
      <eLiterals name="EXPONENTIATION" literal="**"/>
      <eLiterals name="MULTIPLY" value="1" literal="*"/>
      <eLiterals name="DIVIDE" value="2" literal="/"/>
      <eLiterals name="MODULO" value="3" literal="MOD"/>
      <eLiterals name="ADD" value="4" literal="+"/>
      <eLiterals name="SUBTRACT" value="5" literal="-"/>
      <eLiterals name="EQUALITY" value="6" literal="="/>
      <eLiterals name="INEQUALITY" value="7" literal="&lt;>"/>
      <eLiterals name="LESS_THAN" value="8" literal="&lt;"/>
      <eLiterals name="LESS_THAN_OR_EQUAL" value="9" literal="&lt;="/>
      <eLiterals name="GREATER_THAN" value="10" literal=">"/>
      <eLiterals name="GTEATER_THAN_OR_EQUAL" value="11" literal=">="/>
      <eLiterals name="BOOLEAN_AND_SYMBOL" value="12" literal="&amp;"/>
      <eLiterals name="BOOLEAN_AND" value="13" literal="AND"/>
      <eLiterals name="BOOLEAN_EXCLUSIVE_OR" value="14" literal="XOR"/>
      <eLiterals name="BOOLEAN_OR" value="15" literal="OR"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//basics/Exprement #//basics/LabelOrIndex"/>
    <eClassifiers xsi:type="ecore:EClass" name="Index" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lower" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="upper" lowerBound="1"
          eType="#//expressions/Expression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IdExpression" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="path" lowerBound="1"
          eType="#//basics/ConstVar"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralOp" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatand" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QuoteValueOp" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//declarations/Type"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnaryOp" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryOp" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operands" lowerBound="2"
          upperBound="-1" eType="#//expressions/Expression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NaryOp" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operands" lowerBound="2"
          upperBound="-1" eType="#//expressions/Expression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FBInstance" eSuperTypes="#//basics/ConstVar #//basics/LabelOrIndex">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProjectionOp" eSuperTypes="#//expressions/Expression #//basics/ConstVar">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expressions/Expression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="with" eType="#//basics/LabelOrIndex"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
          eType="#//expressions/Expression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Call" eSuperTypes="#//expressions/Expression #//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="callParameters" upperBound="-1"
          eType="#//expressions/Parameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pou" eType="#//declarations/POU"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expressions/Expression"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="statements" nsURI="https://www.formaltech.com/st/api/statements/"
      nsPrefix="statements">
    <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="#//basics/Exprement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Statements">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
          eType="#//statements/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          eType="#//declarations/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expressions/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IfBlock" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//statements/Statements"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseIf" upperBound="-1"
          eType="#//statements/ElseIfBlock" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//statements/Statements"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ElseIfBlock" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="#//expressions/Expression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//statements/Statements"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CaseBlock" eSuperTypes="#//statements/Statements">
      <eStructuralFeatures xsi:type="ecore:EReference" name="selector" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="selection" upperBound="-1"
          eType="#//statements/CaseSelectionBlock" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//statements/Statements"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CaseSelectionBlock" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="label" lowerBound="1"
          eType="#//expressions/List"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" eType="#//statements/Statements"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Iterator" eSuperTypes="#//statements/Statement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ForBlock" eSuperTypes="#//statements/Iterator">
      <eStructuralFeatures xsi:type="ecore:EReference" name="control" eType="#//declarations/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//expressions/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//expressions/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="step" eType="#//expressions/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" eType="#//statements/Statements"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoopBlock" eSuperTypes="#//statements/Iterator">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" eType="#//statements/Statements"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WhileBlock" eSuperTypes="#//statements/LoopBlock"/>
    <eClassifiers xsi:type="ecore:EClass" name="RepeatBlock" eSuperTypes="#//statements/LoopBlock"/>
    <eClassifiers xsi:type="ecore:EClass" name="Exit" eSuperTypes="#//statements/Statement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Return" eSuperTypes="#//statements/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expressions/Expression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Continue" eSuperTypes="#//statements/Statement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Empty" eSuperTypes="#//statements/Statement"/>
  </eSubpackages>
</ecore:EPackage>
